services:
  ui:
    build:
      context: "./ui"
      dockerfile: "Dockerfile"
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=heroes.chrl.uk
  api:
    build:
      context: "./api"
      dockerfile: "Dockerfile"
    ports:
      - 443:443
      - 80:80
