services:
  ui:
    build:
      context: "./ui"
      dockerfile: "Dockerfile"
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=cbarchvm01
      - NGINX_PORT=80
  api:
    build:
      context: "./api"
      dockerfile: "Dockerfile"
    ports:
      - 5152:80
      - 5153:443
