services:
  api:
    build:
      context: "./api"
      dockerfile: "Dockerfile"
    environment:
      - CONNECTION_STRING=DataSource=/app/data/heroes.db
    ports:
      - 5152:80
      - 5153:443
    volumes:
      - type: volume
        source: heroes-data
        target: /app/data
    networks:
      ingress:
        aliases:
          - toh-api
  ui:
    build:
      context: "./ui"
      dockerfile: "Dockerfile"
    depends_on:
      - api
    environment:
      - API_HOST=https://heroes.chrl.uk
      - API_ROUTE=api/v1
    ports:
      - 8080:80
    networks:
      ingress:
        aliases:
          - toh-ui
volumes:
  heroes-data:
networks:
  ingress:
    external: true
