services:
  ui:
    build:
      context: "./ui"
      dockerfile: "Dockerfile"
    ports:
      - 8081:80
    environment:
      - NGINX_HOST=ui
      - NGINX_PORT=80
  api:
    build:
      context: "./api"
      dockerfile: "Dockerfile"
    ports:
      - 5152:80
      - 5153:443
  proxy:
    image: nginx:1.27
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=cbarchvm01
      - NGINX_PORT=80
    volumes:
      - ./proxy/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
