services:
  api:
    build:
      context: "./api"
      dockerfile: "Dockerfile"
    environment:
      - CONNECTION_STRING=DataSource=/app/data/heroes.db
    ports:
      - 5152:80
      - 5153:443
    volumes:
      - type: volume
        source: heroes-data
        target: /app/data
    networks:
      - ingress
  ui:
    build:
      context: "./ui"
      dockerfile: "Dockerfile"
    depends_on:
      - api
    environment:
      - NGINX_HOST=ui
      - NGINX_PORT=80
      - API_HOST=https://heroes.chrl.uk
      - API_ROUTE=api/v1
    ports:
      - 8080:80
    networks:
      - ingress
  proxy:
    image: nginx:1.27
    depends_on:
      - ui
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./proxy/chrl.pem:/etc/ssl/chrl.pem
      - ./proxy/chrl.key:/etc/ssl/chrl.key
    networks:
      - ingress
volumes:
  heroes-data:
networks:
  ingress:
    external: true
